[2023-01-30 13:08:48,893] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2023-01-30 13:08:49,231] INFO [KafkaServer id=4] shutting down (kafka.server.KafkaServer)
[2023-01-30 13:08:49,236] INFO [KafkaServer id=4] Starting controlled shutdown (kafka.server.KafkaServer)
[2023-01-30 13:08:49,623] INFO Unable to read additional data from server sessionid 0x1005b8e7feb0004, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2023-01-30 13:08:49,633] WARN Session 0x1005b8e7feb0001 for server localhost/0:0:0:0:0:0:0:1:49618, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:365)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2023-01-30 13:08:49,754] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2023-01-30 13:08:49,769] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2023-01-30 13:08:50,984] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:49618. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2023-01-30 13:08:50,988] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:49618: Connection refused (org.apache.zookeeper.ClientCnxn)
[2023-01-30 13:08:51,096] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2023-01-30 13:08:51,249] INFO Opening socket connection to server localhost/127.0.0.1:49618. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2023-01-30 13:08:51,251] INFO Socket error occurred: localhost/127.0.0.1:49618: Connection refused (org.apache.zookeeper.ClientCnxn)
